# Generated by Django 4.2.3 on 2023-07-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_myuser_options_myuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
