# Generated by Django 4.2.3 on 2023-07-27 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_step_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_steps', to=settings.AUTH_USER_MODEL),
        ),
    ]
