# Generated by Django 4.2.3 on 2023-07-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_step_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
