# Generated by Django 4.2.3 on 2023-08-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_step_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='step_files/'),
        ),
    ]
