# Generated by Django 4.2.4 on 2023-08-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_step_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/steps/'),
        ),
    ]
