# Generated by Django 4.2.4 on 2024-01-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_project_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
