# Generated by Django 4.2.4 on 2024-01-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_due_date_project_todays_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='sign_sheet',
            field=models.FileField(blank=True, null=True, upload_to='static/steps/'),
        ),
    ]
