# Generated by Django 4.2.4 on 2024-01-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_step_sign_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='assigned_steps_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='myuser',
            name='completed_steps_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
