# Generated by Django 4.2.4 on 2024-01-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_myuser_assigned_steps_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='progress_percentage',
            field=models.BigIntegerField(default=0),
        ),
    ]
