# Generated by Django 4.2.4 on 2024-01-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_step_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='equipment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='vehicle',
            field=models.TextField(blank=True),
        ),
    ]
