# Generated by Django 4.2.4 on 2024-01-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_project_equipment_project_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='assigned_to',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
