# Generated by Django 4.2.4 on 2024-01-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_step_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='static/steps/'),
        ),
        migrations.AddField(
            model_name='step',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='static/steps/'),
        ),
        migrations.AddField(
            model_name='step',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to='static/steps/'),
        ),
    ]
