# Generated by Django 4.2.4 on 2024-02-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_step_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
