# Generated by Django 4.2.4 on 2024-05-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_project_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='equipment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
