# Generated by Django 4.2.4 on 2024-02-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='initial_budget',
            field=models.BooleanField(default=False),
        ),
    ]
