# Generated by Django 4.2.4 on 2024-02-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_job_initial_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='initial_budget',
        ),
        migrations.AddField(
            model_name='budget',
            name='initial_budget',
            field=models.BooleanField(default=False),
        ),
    ]
