# Generated by Django 4.2.4 on 2024-03-22 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_remove_job_initial_budget_budget_initial_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='author',
        ),
        migrations.RemoveField(
            model_name='project',
            name='job',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
