# Generated by Django 4.2.4 on 2024-05-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_project_description_alter_project_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
